---
 - name: Discovery play
   hosts: localhost
   gather_facts: true
   tasks:
    - name: Finding OS name
      shell: "uname"
      register: os_name
    - name: Finding uptime
      shell: "uptime"
      register: up_time
    - name: Displaying Discovery info
      debug:
         msg: "{{inventory_hostname}}, {{ansible_os_family}},  {{ansible_system}}, {{up_time.stdout.split(',')[0].split('up')}}"