---
 - name: Usage of verbosity of debug module
   hosts: all
   tasks:
    - name: verbosity as default
      debug:
        msg: "This is default message"
    - name: verbosity is 2
      debug:
        msg: "verbosity is 2 here"
        verbosity: 2 # we defined verbosity as two it means if we provide -vv minimum two times while running playbook then only the message displayed