---
 - hosts: all
   become: yes
   gather_facts: no
   tasks: 
     - name: Installing httpd
       yum:
         name: httpd
         state: present
     - template:
         src: index.html.j2
         dest: /usr/share/httpd/noindex.index.html
     - name: Starting httpd server
       service: 
          name: httpd
          state: started

# see template module documentation